<a href="https://colab.research.google.com/github/eman3304/project1/blob/main/project3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import sqlite3
from google.colab import files
from IPython.display import display

print("✅ Libraries imported successfully")


print("📂 Upload the CLEANED dataset from Project 1")
print("Example: Cleaned_Dataset.xlsx")

uploaded = files.upload()

file_name = next(iter(uploaded))

print(f"\n✅ File uploaded: {file_name}")



df = pd.read_excel(file_name)

print("\n" + "="*70)
print("DATASET LOADED")
print("="*70)

print(f"Rows    : {df.shape[0]:,}")
print(f"Columns : {df.shape[1]}")

display(df.head())

df.columns = (
    df.columns
    .str.strip()
    .str.replace(" ", "_")
)

if "Date" in df.columns:
    df["Date"] = pd.to_datetime(
        df["Date"],
        errors="coerce"
    )

if "Date" in df.columns:
    df["Date"] = df["Date"].dt.strftime("%Y-%m-%d")



connection = sqlite3.connect("decodelabs_project3.db")

df.to_sql(
    "sales_data",
    connection,
    if_exists="replace",
    index=False
)

print("\n✅ SQL table created successfully: sales_data")


def run_sql(query, title=None):

    if title:
        print("\n" + "="*70)
        print(title)
        print("="*70)

    result = pd.read_sql_query(
        query,
        connection
    )

    display(result)

    return result



run_sql(
    """
    PRAGMA table_info(sales_data);
    """,
    "1. TABLE STRUCTURE"
)



run_sql(
    """
    SELECT *
    FROM sales_data
    LIMIT 10;
    """,
    "2. SELECT - FIRST 10 ROWS"
)



available_columns = set(df.columns)

if {"OrderID", "CustomerID", "Product", "TotalPrice"}.issubset(
    available_columns
):

    run_sql(
        """
        SELECT
            OrderID,
            CustomerID,
            Product,
            TotalPrice
        FROM sales_data
        LIMIT 20;
        """,
        "3. SELECT SPECIFIC COLUMNS"
    )



if "TotalPrice" in available_columns:

    run_sql(
        """
        SELECT *
        FROM sales_data
        WHERE TotalPrice > 100
        ORDER BY TotalPrice DESC;
        """,
        "4. WHERE - ORDERS ABOVE 100"
    )


if {"Product", "TotalPrice"}.issubset(available_columns):

    run_sql(
        """
        SELECT
            Product,
            TotalPrice
        FROM sales_data
        WHERE TotalPrice > 50
        ORDER BY TotalPrice DESC;
        """,
        "5. WHERE + ORDER BY"
    )



if "OrderID" in available_columns:

    run_sql(
        """
        SELECT
            COUNT(*) AS Total_Orders
        FROM sales_data;
        """,
        "6. COUNT - TOTAL ORDERS"
    )


if "CustomerID" in available_columns:

    run_sql(
        """
        SELECT
            COUNT(DISTINCT CustomerID) AS Unique_Customers
        FROM sales_data;
        """,
        "7. COUNT DISTINCT - UNIQUE CUSTOMERS"
    )


if "TotalPrice" in available_columns:

    run_sql(
        """
        SELECT
            ROUND(SUM(TotalPrice), 2) AS Total_Revenue
        FROM sales_data;
        """,
        "8. SUM - TOTAL REVENUE"
    )



if "TotalPrice" in available_columns:

    run_sql(
        """
        SELECT
            ROUND(AVG(TotalPrice), 2) AS Average_Order_Value
        FROM sales_data;
        """,
        "9. AVG - AVERAGE ORDER VALUE"
    )


if "TotalPrice" in available_columns:

    run_sql(
        """
        SELECT
            ROUND(MIN(TotalPrice), 2) AS Minimum_Order,
            ROUND(MAX(TotalPrice), 2) AS Maximum_Order
        FROM sales_data;
        """,
        "10. MIN AND MAX ORDER VALUE"
    )



if {"Product", "OrderID", "Quantity", "TotalPrice"}.issubset(
    available_columns
):

    product_analysis = run_sql(
        """
        SELECT
            Product,
            COUNT(*) AS Orders,
            SUM(Quantity) AS Total_Quantity,
            ROUND(SUM(TotalPrice), 2) AS Total_Revenue,
            ROUND(AVG(TotalPrice), 2) AS Average_Order_Value
        FROM sales_data
        GROUP BY Product
        ORDER BY Total_Revenue DESC;
        """,
        "11. GROUP BY - PRODUCT PERFORMANCE"
    )


if {"OrderStatus", "OrderID", "TotalPrice"}.issubset(
    available_columns
):

    status_analysis = run_sql(
        """
        SELECT
            OrderStatus,
            COUNT(*) AS Orders,
            ROUND(SUM(TotalPrice), 2) AS Revenue,
            ROUND(AVG(TotalPrice), 2) AS Average_Order_Value
        FROM sales_data
        GROUP BY OrderStatus
        ORDER BY Orders DESC;
        """,
        "12. GROUP BY - ORDER STATUS"
    )


if {"PaymentMethod", "OrderID", "TotalPrice"}.issubset(
    available_columns
):

    payment_analysis = run_sql(
        """
        SELECT
            PaymentMethod,
            COUNT(*) AS Orders,
            ROUND(SUM(TotalPrice), 2) AS Revenue,
            ROUND(AVG(TotalPrice), 2) AS Average_Order_Value
        FROM sales_data
        GROUP BY PaymentMethod
        ORDER BY Revenue DESC;
        """,
        "13. GROUP BY - PAYMENT METHOD"
    )


if {"ReferralSource", "OrderID", "TotalPrice"}.issubset(
    available_columns
):

    referral_analysis = run_sql(
        """
        SELECT
            ReferralSource,
            COUNT(*) AS Orders,
            ROUND(SUM(TotalPrice), 2) AS Revenue,
            ROUND(AVG(TotalPrice), 2) AS Average_Order_Value
        FROM sales_data
        GROUP BY ReferralSource
        ORDER BY Revenue DESC;
        """,
        "14. GROUP BY - REFERRAL SOURCE"
    )


if {"CouponCode", "OrderID", "TotalPrice"}.issubset(
    available_columns
):

    coupon_analysis = run_sql(
        """
        SELECT
            CouponCode,
            COUNT(*) AS Orders,
            ROUND(SUM(TotalPrice), 2) AS Revenue,
            ROUND(AVG(TotalPrice), 2) AS Average_Order_Value
        FROM sales_data
        GROUP BY CouponCode
        ORDER BY Orders DESC;
        """,
        "15. GROUP BY - COUPON PERFORMANCE"
    )


if {"Product", "TotalPrice"}.issubset(
    available_columns
):

    run_sql(
        """
        SELECT
            Product,
            ROUND(SUM(TotalPrice), 2) AS Total_Revenue
        FROM sales_data
        GROUP BY Product
        HAVING SUM(TotalPrice) > 5000
        ORDER BY Total_Revenue DESC;
        """,
        "16. HAVING - PRODUCTS ABOVE REVENUE THRESHOLD"
    )



if {"CustomerID", "OrderID", "TotalPrice"}.issubset(
    available_columns
):

    customer_analysis = run_sql(
        """
        SELECT
            CustomerID,
            COUNT(*) AS Number_of_Orders,
            ROUND(SUM(TotalPrice), 2) AS Total_Spending,
            ROUND(AVG(TotalPrice), 2) AS Average_Order_Value
        FROM sales_data
        GROUP BY CustomerID
        ORDER BY Total_Spending DESC
        LIMIT 20;
        """,
        "17. TOP 20 CUSTOMERS BY SPENDING"
    )



if {"CustomerID", "OrderID"}.issubset(
    available_columns
):

    run_sql(
        """
        SELECT
            CustomerID,
            COUNT(*) AS Number_of_Orders
        FROM sales_data
        GROUP BY CustomerID
        HAVING COUNT(*) > 1
        ORDER BY Number_of_Orders DESC;
        """,
        "18. REPEAT CUSTOMERS"
    )



if {"Date", "TotalPrice"}.issubset(
    available_columns
):

    monthly_analysis = run_sql(
        """
        SELECT
            strftime('%Y-%m', Date) AS Month,
            COUNT(*) AS Orders,
            ROUND(SUM(TotalPrice), 2) AS Revenue,
            ROUND(AVG(TotalPrice), 2) AS Average_Order_Value
        FROM sales_data
        WHERE Date IS NOT NULL
        GROUP BY strftime('%Y-%m', Date)
        ORDER BY Month;
        """,
        "19. MONTHLY SALES ANALYSIS"
    )



if {"Date", "TotalPrice"}.issubset(
    available_columns
):

    run_sql(
        """
        SELECT
            strftime('%Y-%m', Date) AS Month,
            ROUND(SUM(TotalPrice), 2) AS Revenue
        FROM sales_data
        WHERE Date IS NOT NULL
        GROUP BY strftime('%Y-%m', Date)
        ORDER BY Revenue DESC
        LIMIT 1;
        """,
        "20. HIGHEST REVENUE MONTH"
    )


if {"Product", "Quantity"}.issubset(
    available_columns
):

    run_sql(
        """
        SELECT
            Product,
            SUM(Quantity) AS Total_Quantity
        FROM sales_data
        GROUP BY Product
        ORDER BY Total_Quantity DESC
        LIMIT 10;
        """,
        "21. TOP PRODUCTS BY QUANTITY SOLD"
    )


if {"OrderID", "Product", "TotalPrice"}.issubset(
    available_columns
):

    run_sql(
        """
        SELECT
            OrderID,
            Product,
            TotalPrice
        FROM sales_data
        ORDER BY TotalPrice DESC
        LIMIT 10;
        """,
        "22. TOP 10 HIGHEST-VALUE ORDERS"
    )


if "TotalPrice" in available_columns:

    run_sql(
        """
        SELECT
            CASE
                WHEN TotalPrice < 50 THEN 'Low Value'
                WHEN TotalPrice < 100 THEN 'Medium Value'
                ELSE 'High Value'
            END AS Order_Value_Category,

            COUNT(*) AS Orders,

            ROUND(SUM(TotalPrice), 2) AS Revenue,

            ROUND(AVG(TotalPrice), 2) AS Average_Order_Value

        FROM sales_data

        GROUP BY
            CASE
                WHEN TotalPrice < 50 THEN 'Low Value'
                WHEN TotalPrice < 100 THEN 'Medium Value'
                ELSE 'High Value'
            END

        ORDER BY Revenue DESC;
        """,
        "23. ORDER VALUE SEGMENTATION"
    )


if {
    "Product",
    "PaymentMethod",
    "TotalPrice"
}.issubset(available_columns):

    run_sql(
        """
        SELECT
            Product,
            PaymentMethod,
            COUNT(*) AS Orders,
            ROUND(SUM(TotalPrice), 2) AS Revenue,
            ROUND(AVG(TotalPrice), 2) AS Average_Order_Value

        FROM sales_data

        GROUP BY
            Product,
            PaymentMethod

        ORDER BY
            Revenue DESC;
        """,
        "24. PRODUCT + PAYMENT METHOD ANALYSIS"
    )


print("\n" + "="*70)
print("25. SQL BUSINESS SUMMARY")
print("="*70)

summary_query = """
SELECT
    COUNT(*) AS Total_Orders,
    COUNT(DISTINCT CustomerID) AS Unique_Customers,
    ROUND(SUM(TotalPrice), 2) AS Total_Revenue,
    ROUND(AVG(TotalPrice), 2) AS Average_Order_Value,
    ROUND(MIN(TotalPrice), 2) AS Minimum_Order,
    ROUND(MAX(TotalPrice), 2) AS Maximum_Order
FROM sales_data;
"""

if {
    "CustomerID",
    "TotalPrice"
}.issubset(available_columns):

    business_summary = run_sql(
        summary_query,
        "BUSINESS SUMMARY"
    )


output_file = "DecodeLabs_Project_3_SQL_Analysis.xlsx"

with pd.ExcelWriter(
    output_file,
    engine="openpyxl"
) as writer:

    df.to_excel(
        writer,
        sheet_name="SQL_Data",
        index=False
    )

    if "product_analysis" in locals():
        product_analysis.to_excel(
            writer,
            sheet_name="Product_Analysis",
            index=False
        )

    if "status_analysis" in locals():
        status_analysis.to_excel(
            writer,
            sheet_name="Order_Status",
            index=False
        )

    if "payment_analysis" in locals():
        payment_analysis.to_excel(
            writer,
            sheet_name="Payment_Method",
            index=False
        )

    if "referral_analysis" in locals():
        referral_analysis.to_excel(
            writer,
            sheet_name="Referral_Source",
            index=False
        )

    if "coupon_analysis" in locals():
        coupon_analysis.to_excel(
            writer,
            sheet_name="Coupon_Analysis",
            index=False
        )

    if "customer_analysis" in locals():
        customer_analysis.to_excel(
            writer,
            sheet_name="Top_Customers",
            index=False
        )

    if "monthly_analysis" in locals():
        monthly_analysis.to_excel(
            writer,
            sheet_name="Monthly_Analysis",
            index=False
        )

    if "business_summary" in locals():
        business_summary.to_excel(
            writer,
            sheet_name="Business_Summary",
            index=False
        )


connection.close()


print("\n" + "="*70)
print("PROJECT 3 COMPLETED")
print("="*70)

print(f"✅ SQL analysis file created: {output_file}")

files.download(output_file)

print("\n🎉 DecodeLabs Project 3 - SQL Data Analysis completed successfully!")

✅ Libraries imported successfully
📂 Upload the CLEANED dataset from Project 1
Example: Cleaned_Dataset.xlsx

Saving Cleaned_Dataset.xlsx to Cleaned_Dataset.xlsx

✅ File uploaded: Cleaned_Dataset.xlsx

======================================================================
DATASET LOADED
======================================================================
Rows    : 1,200
Columns : 14

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

✅ SQL table created successfully: sales_data

======================================================================
1. TABLE STRUCTURE
======================================================================

    cid             name     type  notnull dflt_value  pk
0     0          OrderID     TEXT        0       None   0
1     1             Date     TEXT        0       None   0
2     2       CustomerID     TEXT        0       None   0
3     3          Product     TEXT        0       None   0
4     4         Quantity  INTEGER        0       None   0
5     5        UnitPrice     REAL        0       None   0
6     6  ShippingAddress     TEXT        0       None   0
7     7    PaymentMethod     TEXT        0       None   0
8     8      OrderStatus     TEXT        0       None   0
9     9   TrackingNumber     TEXT        0       None   0
10   10      ItemsInCart  INTEGER        0       None   0
11   11       CouponCode     TEXT        0       None   0
12   12   ReferralSource     TEXT        0       None   0
13   13       TotalPrice     REAL        0       None   0

======================================================================
2. SELECT - FIRST 10 ROWS
======================================================================

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
5,ORD200005,2023-10-23,C37249,Phone,2,245.86,934 Main St,Credit Card,Shipped,TRK72976927,4,SAVE10,Instagram,491.72
6,ORD200006,2025-06-17,C83492,Laptop,1,664.42,986 Main St,Gift Card,Returned,TRK96417362,6,SAVE10,Facebook,664.42
7,ORD200007,2023-05-12,C41460,Monitor,5,149.55,706 Main St,Cash,Shipped,TRK78809193,9,FREESHIP,Facebook,747.75
8,ORD200008,2025-04-02,C26817,Phone,2,134.28,904 Main St,Gift Card,Cancelled,TRK61042692,2,No Coupon,Email,268.56
9,ORD200009,2023-11-21,C31946,Desk,4,509.38,102 Main St,Credit Card,Shipped,TRK33478363,6,SAVE10,Google,2037.52

======================================================================
3. SELECT SPECIFIC COLUMNS
======================================================================

      OrderID CustomerID  Product  TotalPrice
0   ORD200000     C72649  Monitor     2853.10
1   ORD200001     C75739    Phone      302.70
2   ORD200002     C81728   Tablet     2753.40
3   ORD200003     C33540    Chair      273.19
4   ORD200004     C81840  Printer     2504.04
5   ORD200005     C37249    Phone      491.72
6   ORD200006     C83492   Laptop      664.42
7   ORD200007     C41460  Monitor      747.75
8   ORD200008     C26817    Phone      268.56
9   ORD200009     C31946     Desk     2037.52
10  ORD200010     C43443   Tablet     3129.85
11  ORD200011     C93861  Monitor      147.42
12  ORD200012     C38785  Monitor      361.00
13  ORD200013     C88348   Laptop      604.47
14  ORD200014     C98474   Tablet      786.66
15  ORD200015     C39416  Printer      473.96
16  ORD200016     C28976  Printer     1067.62
17  ORD200017     C60672   Tablet      423.40
18  ORD200018     C84329     Desk      431.44
19  ORD200019     C14552  Monitor     1120.00

======================================================================
4. WHERE - ORDERS ABOVE 100
======================================================================

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200789,2023-08-17,C57276,Tablet,5,691.28,183 Main St,Online,Delivered,TRK75899752,10,SAVE10,Email,3456.40
1,ORD201122,2023-06-07,C38840,Monitor,5,678.19,766 Main St,Online,Returned,TRK32496970,8,No Coupon,Facebook,3390.95
2,ORD200632,2023-05-02,C67260,Laptop,5,678.16,463 Main St,Gift Card,Delivered,TRK38229104,7,WINTER15,Facebook,3390.80
3,ORD200469,2023-11-26,C13877,Chair,5,676.98,893 Main St,Cash,Cancelled,TRK17254691,5,No Coupon,Facebook,3384.90
4,ORD200328,2023-02-28,C18404,Tablet,5,674.04,546 Main St,Online,Cancelled,TRK89401624,7,SAVE10,Google,3370.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1132,ORD200710,2024-07-22,C48790,Laptop,5,21.54,113 Main St,Gift Card,Returned,TRK19086608,10,No Coupon,Google,107.70
1133,ORD201195,2024-06-20,C21126,Desk,1,107.04,392 Main St,Credit Card,Cancelled,TRK38009181,6,FREESHIP,Google,107.04
1134,ORD200975,2023-05-18,C70529,Desk,1,105.92,974 Main St,Gift Card,Returned,TRK82165408,6,SAVE10,Email,105.92
1135,ORD200602,2024-03-05,C35852,Tablet,4,26.04,982 Main St,Online,Pending,TRK64660134,5,SAVE10,Instagram,104.16
1136,ORD200479,2023-02-18,C87011,Monitor,4,25.29,943 Main St,Credit Card,Pending,TRK21429162,8,No Coupon,Google,101.16

======================================================================
5. WHERE + ORDER BY
======================================================================

      Product  TotalPrice
0      Tablet     3456.40
1     Monitor     3390.95
2      Laptop     3390.80
3       Chair     3384.90
4      Tablet     3370.20
...       ...         ...
1175   Laptop       57.10
1176   Tablet       56.20
1177   Tablet       53.00
1178  Printer       52.54
1179   Laptop       51.73

[1180 rows x 2 columns]

======================================================================
6. COUNT - TOTAL ORDERS
======================================================================

   Total_Orders
0          1200

======================================================================
7. COUNT DISTINCT - UNIQUE CUSTOMERS
======================================================================

   Unique_Customers
0              1189

======================================================================
8. SUM - TOTAL REVENUE
======================================================================

   Total_Revenue
0     1264761.96

======================================================================
9. AVG - AVERAGE ORDER VALUE
======================================================================

   Average_Order_Value
0              1053.97

======================================================================
10. MIN AND MAX ORDER VALUE
======================================================================

   Minimum_Order  Maximum_Order
0          11.39         3456.4

======================================================================
11. GROUP BY - PRODUCT PERFORMANCE
======================================================================

   Product  Orders  Total_Quantity  Total_Revenue  Average_Order_Value
0    Chair     178             562      195620.11              1098.99
1  Printer     181             542      195612.61              1080.73
2   Laptop     173             535      192126.56              1110.56
3   Tablet     179             497      186568.95              1042.28
4  Monitor     163             480      175651.41              1077.62
5     Desk     170             508      167459.93               985.06
6    Phone     156             411      151722.39               972.58

======================================================================
12. GROUP BY - ORDER STATUS
======================================================================

  OrderStatus  Orders    Revenue  Average_Order_Value
0   Cancelled     250  276396.21              1105.58
1    Returned     247  243277.70               984.93
2     Pending     237  256328.15              1081.55
3     Shipped     235  246159.58              1047.49
4   Delivered     231  242600.32              1050.22

======================================================================
13. GROUP BY - PAYMENT METHOD
======================================================================

  PaymentMethod  Orders    Revenue  Average_Order_Value
0   Credit Card     234  263847.63              1127.55
1        Online     258  262442.94              1017.22
2          Cash     246  259786.29              1056.04
3     Gift Card     230  246323.92              1070.97
4    Debit Card     232  232361.18              1001.56

======================================================================
14. GROUP BY - REFERRAL SOURCE
======================================================================

  ReferralSource  Orders    Revenue  Average_Order_Value
0      Instagram     259  275285.45              1062.88
1          Email     250  261808.55              1047.23
2         Google     241  250441.48              1039.18
3       Facebook     228  250410.90              1098.29
4       Referral     222  226815.58              1021.69

======================================================================
15. GROUP BY - COUPON PERFORMANCE
======================================================================

  CouponCode  Orders    Revenue  Average_Order_Value
0   FREESHIP     313  335036.99              1070.41
1  No Coupon     309  322401.41              1043.37
2   WINTER15     292  302483.54              1035.90
3     SAVE10     286  304840.02              1065.87

======================================================================
16. HAVING - PRODUCTS ABOVE REVENUE THRESHOLD
======================================================================

   Product  Total_Revenue
0    Chair      195620.11
1  Printer      195612.61
2   Laptop      192126.56
3   Tablet      186568.95
4  Monitor      175651.41
5     Desk      167459.93
6    Phone      151722.39

======================================================================
17. TOP 20 CUSTOMERS BY SPENDING
======================================================================

   CustomerID  Number_of_Orders  Total_Spending  Average_Order_Value
0      C38840                 2         5723.23              2861.61
1      C57276                 1         3456.40              3456.40
2      C67260                 1         3390.80              3390.80
3      C13877                 1         3384.90              3384.90
4      C18404                 1         3370.20              3370.20
5      C16775                 1         3353.75              3353.75
6      C65986                 1         3352.40              3352.40
7      C47778                 1         3334.00              3334.00
8      C59183                 1         3322.55              3322.55
9      C25276                 1         3313.90              3313.90
10     C53464                 1         3299.25              3299.25
11     C13108                 1         3293.85              3293.85
12     C88029                 1         3277.75              3277.75
13     C27202                 1         3267.35              3267.35
14     C35987                 1         3267.30              3267.30
15     C36725                 1         3253.60              3253.60
16     C87281                 1         3243.25              3243.25
17     C84331                 1         3223.20              3223.20
18     C73575                 1         3219.45              3219.45
19     C88205                 1         3215.15              3215.15

======================================================================
18. REPEAT CUSTOMERS
======================================================================

   CustomerID  Number_of_Orders
0      C98474                 2
1      C97593                 2
2      C94569                 2
3      C91155                 2
4      C70659                 2
5      C56969                 2
6      C46651                 2
7      C38840                 2
8      C35852                 2
9      C21191                 2
10     C14847                 2

======================================================================
19. MONTHLY SALES ANALYSIS
======================================================================

      Month  Orders   Revenue  Average_Order_Value
0   2023-01      47  56685.75              1206.08
1   2023-02      37  40117.66              1084.26
2   2023-03      43  48609.37              1130.45
3   2023-04      31  27751.71               895.22
4   2023-05      49  63836.84              1302.79
5   2023-06      45  49500.19              1100.00
6   2023-07      44  42820.66               973.20
7   2023-08      51  54352.14              1065.73
8   2023-09      29  29526.67              1018.16
9   2023-10      47  52607.85              1119.32
10  2023-11      41  43079.67              1050.72
11  2023-12      46  43754.73               951.19
12  2024-01      32  38528.08              1204.00
13  2024-02      32  36909.57              1153.42
14  2024-03      36  36030.90              1000.86
15  2024-04      50  49613.14               992.26
16  2024-05      34  27909.11               820.86
17  2024-06      53  68068.54              1284.31
18  2024-07      43  42963.98               999.16
19  2024-08      28  31991.07              1142.54
20  2024-09      44  39794.98               904.43
21  2024-10      31  37226.97              1200.87
22  2024-11      35  32413.76               926.11
23  2024-12      41  38785.77               945.99
24  2025-01      27  29099.40              1077.76
25  2025-02      37  35317.55               954.53
26  2025-03      49  39200.66               800.01
27  2025-04      32  31821.20               994.41
28  2025-05      37  43396.64              1172.88
29  2025-06      49  53047.40              1082.60

======================================================================
20. HIGHEST REVENUE MONTH
======================================================================

     Month   Revenue
0  2024-06  68068.54

======================================================================
21. TOP PRODUCTS BY QUANTITY SOLD
======================================================================

   Product  Total_Quantity
0    Chair             562
1  Printer             542
2   Laptop             535
3     Desk             508
4   Tablet             497
5  Monitor             480
6    Phone             411

======================================================================
22. TOP 10 HIGHEST-VALUE ORDERS
======================================================================

     OrderID  Product  TotalPrice
0  ORD200789   Tablet     3456.40
1  ORD201122  Monitor     3390.95
2  ORD200632   Laptop     3390.80
3  ORD200469    Chair     3384.90
4  ORD200328   Tablet     3370.20
5  ORD200107  Printer     3353.75
6  ORD200326   Laptop     3352.40
7  ORD201065  Printer     3334.00
8  ORD201031    Phone     3322.55
9  ORD200463   Laptop     3313.90

======================================================================
23. ORDER VALUE SEGMENTATION
======================================================================

  Order_Value_Category  Orders     Revenue  Average_Order_Value
0           High Value    1137  1260865.23              1108.94
1         Medium Value      43     3289.73                76.51
2            Low Value      20      607.00                30.35

======================================================================
24. PRODUCT + PAYMENT METHOD ANALYSIS
======================================================================

    Product PaymentMethod  Orders   Revenue  Average_Order_Value
0     Chair        Online      47  54341.91              1156.21
1    Laptop          Cash      45  48676.40              1081.70
2   Printer          Cash      41  46940.27              1144.88
3   Printer   Credit Card      39  43289.52              1109.99
4    Tablet        Online      47  43275.77               920.76
5   Monitor   Credit Card      34  42473.64              1249.22
6    Laptop     Gift Card      33  42057.39              1274.47
7   Printer        Online      39  39538.50              1013.81
8      Desk     Gift Card      39  39498.39              1012.78
9    Tablet    Debit Card      36  38737.86              1076.05
10    Chair     Gift Card      36  38064.35              1057.34
11   Tablet          Cash      35  37777.76              1079.36
12   Tablet   Credit Card      31  37579.89              1212.25
13     Desk   Credit Card      37  37473.98              1012.81
14    Chair          Cash      34  35902.59              1055.96
15   Laptop    Debit Card      36  35713.68               992.05
16    Chair   Credit Card      30  35405.05              1180.17
17   Laptop   Credit Card      28  35308.12              1261.00
18  Monitor        Online      34  35239.46              1036.45
19  Monitor     Gift Card      29  33301.19              1148.32
20  Printer    Debit Card      33  33165.09              1005.00
21  Monitor          Cash      34  32847.01               966.09
22  Printer     Gift Card      29  32679.23              1126.87
23    Phone   Credit Card      35  32317.43               923.36
24    Chair    Debit Card      31  31906.21              1029.23
25  Monitor    Debit Card      32  31790.11               993.44
26    Phone    Debit Card      30  31731.75              1057.72
27     Desk          Cash      33  31644.97               958.94
28    Phone     Gift Card      34  31525.70               927.23
29   Laptop        Online      31  30370.97               979.71
30    Phone        Online      33  30150.22               913.64
31     Desk        Online      27  29526.11              1093.56
32     Desk    Debit Card      34  29316.48               862.25
33   Tablet     Gift Card      30  29197.67               973.26
34    Phone          Cash      24  25997.29              1083.22

======================================================================
25. SQL BUSINESS SUMMARY
======================================================================

======================================================================
BUSINESS SUMMARY
======================================================================

,Total_Orders,Unique_Customers,Total_Revenue,Average_Order_Value,Minimum_Order,Maximum_Order
0,1200,1189,1264761.96,1053.97,11.39,3456.4

======================================================================
PROJECT 3 COMPLETED
======================================================================
✅ SQL analysis file created: DecodeLabs_Project_3_SQL_Analysis.xlsx

🎉 DecodeLabs Project 3 - SQL Data Analysis completed successfully!